#
import ee

BANDS_SPECIFICATIONS = {
    "biomes": [
        ["blue_median", "uint16"],
        ["blue_median_wet", "uint16"],
        ["blue_median_dry", "uint16"],
        ["blue_min", "uint16"],
        ["blue_stdDev", "int32"],
        ["green_median", "uint16"],
        ["green_median_dry", "uint16"],
        ["green_median_wet", "uint16"],
        ["green_median_texture", "int16"],
        ["green_min", "uint16"],
        ["green_stdDev", "int32"],
        ["red_median", "uint16"],
        ["red_median_dry", "uint16"],
        ["red_min", "uint16"],
        ["red_median_wet", "uint16"],
        ["red_stdDev", "int32"],
        ["nir_median", "uint16"],
        ["nir_median_dry", "uint16"],
        ["nir_median_wet", "uint16"],
        ["nir_min", "uint16"],
        ["nir_stdDev", "int32"],
        ["swir1_median", "uint16"],
        ["swir1_median_dry", "uint16"],
        ["swir1_median_wet", "uint16"],
        ["swir1_min", "uint16"],
        ["swir1_stdDev", "int32"],
        ["swir2_median", "uint16"],
        ["swir2_median_wet", "uint16"],
        ["swir2_median_dry", "uint16"],
        ["swir2_min", "uint16"],
        ["swir2_stdDev", "int32"],
        ["ndvi_median_dry", "uint16"],
        ["ndvi_median_wet", "uint16"],
        ["ndvi_median", "uint16"],
        ["ndvi_amp", "uint16"],
        ["ndvi_stdDev", "int32"],
        ["ndwi_median", "uint16"],
        ["ndwi_median_dry", "uint16"],
        ["ndwi_median_wet", "uint16"],
        ["ndwi_amp", "uint16"],
        ["ndwi_stdDev", "int32"],
        ["evi2_median", "uint16"],
        ["evi2_median_dry", "uint16"],
        ["evi2_median_wet", "uint16"],
        ["evi2_amp", "uint16"],
        ["evi2_stdDev", "int32"],
        ["savi_median_dry", "uint16"],
        ["savi_median_wet", "uint16"],
        ["savi_median", "uint16"],
        ["savi_stdDev", "int32"],
        ["pri_median_dry", "uint16"],
        ["pri_median", "uint16"],
        ["pri_median_wet", "uint16"],
        ["gcvi_median", "int32"],
        ["gcvi_median_dry", "int32"],
        ["gcvi_median_wet", "int32"],
        ["gcvi_stdDev", "int32"],
        ["hallcover_median", "uint32"],
        ["hallcover_stdDev", "int32"],
        ["cai_median", "uint16"],
        ["cai_median_dry", "uint16"],
        ["cai_stdDev", "int32"],
        ["gv_median", "uint8"],
        ["gv_median_dry", "uint8"],
        ["gv_median_wet", "uint8"],
        ["gv_max", "uint8"],
        ["gv_min", "uint8"],
        ["gv_amp", "uint8"],
        ["gv_stdDev", "int32"],
        ["gvs_median", "uint8"],
        ["gvs_median_dry", "uint8"],
        ["gvs_median_wet", "uint8"],
        ["gvs_max", "uint8"],
        ["gvs_min", "uint8"],
        ["gvs_amp", "uint8"],
        ["gvs_stdDev", "int32"],
        ["npv_median", "uint8"],
        ["npv_median_dry", "uint8"],
        ["npv_median_wet", "uint8"],
        ["npv_max", "uint8"],
        ["npv_min", "uint8"],
        ["npv_amp", "uint8"],
        ["npv_stdDev", "int32"],
        ["soil_median", "uint8"],
        ["soil_median_dry", "uint8"],
        ["soil_median_wet", "uint8"],
        ["soil_max", "uint8"],
        ["soil_min", "uint8"],
        ["soil_amp", "uint8"],
        ["soil_stdDev", "int32"],
        ["cloud_median", "uint8"],
        ["cloud_median_dry", "uint8"],
        ["cloud_median_wet", "uint8"],
        ["cloud_max", "uint8"],
        ["cloud_min", "uint8"],
        ["cloud_amp", "uint8"],
        ["cloud_stdDev", "int32"],
        ["shade_median", "uint8"],
        ["shade_median_dry", "uint8"],
        ["shade_median_wet", "uint8"],
        ["shade_max", "uint8"],
        ["shade_min", "uint8"],
        ["shade_amp", "uint8"],
        ["shade_stdDev", "int32"],
        ["ndfi_median", "uint8"],
        ["ndfi_median_dry", "uint8"],
        ["ndfi_median_wet", "uint8"],
        ["ndfi_max", "uint8"],
        ["ndfi_min", "uint8"],
        ["ndfi_amp", "uint8"],
        ["ndfi_stdDev", "int32"],
        ["sefi_median", "uint8"],
        ["sefi_stdDev", "int32"],
        ["sefi_median_dry", "uint8"],
        ["wefi_median", "uint8"],
        ["wefi_median_wet", "uint8"],
        ["wefi_amp", "uint8"],
        ["wefi_stdDev", "int32"],
        # ["fns_median", "uint8"],
        # ["fns_median_dry", "uint8"],
        # ["fns_stdDev", "int32"],
        ["slope", "int16"]
    ],

    "biomes_s2": [
        ["blue_median", "uint16"],
        ["blue_median_wet", "uint16"],
        ["blue_median_dry", "uint16"],
        ["blue_min", "uint16"],
        ["blue_stdDev", "int32"],
        ["green_median", "uint16"],
        ["green_median_dry", "uint16"],
        ["green_median_wet", "uint16"],
        ["green_median_texture", "int16"],
        ["green_min", "uint16"],
        ["green_stdDev", "int32"],
        ["red_median", "uint16"],
        ["red_median_dry", "uint16"],
        ["red_min", "uint16"],
        ["red_median_wet", "uint16"],
        ["red_stdDev", "int32"],
        ["nir_median", "uint16"],
        ["nir_median_dry", "uint16"],
        ["nir_median_wet", "uint16"],
        ["nir_min", "uint16"],
        ["nir_stdDev", "int32"],

        ["red_edge_1_median", "uint16"],
        ["red_edge_1_median_dry", "uint16"],
        ["red_edge_1_median_wet", "uint16"],
        ["red_edge_1_min", "uint16"],
        ["red_edge_1_stdDev", "int32"],

        ["red_edge_2_median", "uint16"],
        ["red_edge_2_median_dry", "uint16"],
        ["red_edge_2_median_wet", "uint16"],
        ["red_edge_2_min", "uint16"],
        ["red_edge_2_stdDev", "int32"],

        ["red_edge_3_median", "uint16"],
        ["red_edge_3_median_dry", "uint16"],
        ["red_edge_3_median_wet", "uint16"],
        ["red_edge_3_min", "uint16"],
        ["red_edge_3_stdDev", "int32"],

        ["red_edge_4_median", "uint16"],
        ["red_edge_4_median_dry", "uint16"],
        ["red_edge_4_median_wet", "uint16"],
        ["red_edge_4_min", "uint16"],
        ["red_edge_4_stdDev", "int32"],

        ["swir1_median", "uint16"],
        ["swir1_median_dry", "uint16"],
        ["swir1_median_wet", "uint16"],
        ["swir1_min", "uint16"],
        ["swir1_stdDev", "int32"],
        ["swir2_median", "uint16"],
        ["swir2_median_wet", "uint16"],
        ["swir2_median_dry", "uint16"],
        ["swir2_min", "uint16"],
        ["swir2_stdDev", "int32"],
        ["ndvi_median_dry", "uint16"],
        ["ndvi_median_wet", "uint16"],
        ["ndvi_median", "uint16"],
        ["ndvi_amp", "uint16"],
        ["ndvi_stdDev", "int32"],
        ["ndwi_median", "uint16"],
        ["ndwi_median_dry", "uint16"],
        ["ndwi_median_wet", "uint16"],
        ["ndwi_amp", "uint16"],
        ["ndwi_stdDev", "int32"],
        ["evi2_median", "uint16"],
        ["evi2_median_dry", "uint16"],
        ["evi2_median_wet", "uint16"],
        ["evi2_amp", "uint16"],
        ["evi2_stdDev", "int32"],
        ["savi_median_dry", "uint16"],
        ["savi_median_wet", "uint16"],
        ["savi_median", "uint16"],
        ["savi_stdDev", "int32"],
        ["pri_median_dry", "uint16"],
        ["pri_median", "uint16"],
        ["pri_median_wet", "uint16"],
        ["gcvi_median", "int32"],
        ["gcvi_median_dry", "int32"],
        ["gcvi_median_wet", "int32"],
        ["gcvi_stdDev", "int32"],
        ["hallcover_median", "uint32"],
        ["hallcover_stdDev", "int32"],
        ["cai_median", "uint16"],
        ["cai_median_dry", "uint16"],
        ["cai_stdDev", "int32"],
        ["gv_median", "uint8"],
        ["gv_median_dry", "uint8"],
        ["gv_median_wet", "uint8"],
        ["gv_max", "uint8"],
        ["gv_min", "uint8"],
        ["gv_amp", "uint8"],
        ["gv_stdDev", "int32"],
        ["gvs_median", "uint8"],
        ["gvs_median_dry", "uint8"],
        ["gvs_median_wet", "uint8"],
        ["gvs_max", "uint8"],
        ["gvs_min", "uint8"],
        ["gvs_amp", "uint8"],
        ["gvs_stdDev", "int32"],
        ["npv_median", "uint8"],
        ["npv_median_dry", "uint8"],
        ["npv_median_wet", "uint8"],
        ["npv_max", "uint8"],
        ["npv_min", "uint8"],
        ["npv_amp", "uint8"],
        ["npv_stdDev", "int32"],
        ["soil_median", "uint8"],
        ["soil_median_dry", "uint8"],
        ["soil_median_wet", "uint8"],
        ["soil_max", "uint8"],
        ["soil_min", "uint8"],
        ["soil_amp", "uint8"],
        ["soil_stdDev", "int32"],
        ["cloud_median", "uint8"],
        ["cloud_median_dry", "uint8"],
        ["cloud_median_wet", "uint8"],
        ["cloud_max", "uint8"],
        ["cloud_min", "uint8"],
        ["cloud_amp", "uint8"],
        ["cloud_stdDev", "int32"],
        ["shade_median", "uint8"],
        ["shade_median_dry", "uint8"],
        ["shade_median_wet", "uint8"],
        ["shade_max", "uint8"],
        ["shade_min", "uint8"],
        ["shade_amp", "uint8"],
        ["shade_stdDev", "int32"],
        ["ndfi_median", "uint8"],
        ["ndfi_median_dry", "uint8"],
        ["ndfi_median_wet", "uint8"],
        ["ndfi_max", "uint8"],
        ["ndfi_min", "uint8"],
        ["ndfi_amp", "uint8"],
        ["ndfi_stdDev", "int32"],
        ["sefi_median", "uint8"],
        ["sefi_stdDev", "int32"],
        ["sefi_median_dry", "uint8"],
        ["wefi_median", "uint8"],
        ["wefi_median_wet", "uint8"],
        ["wefi_amp", "uint8"],
        ["wefi_stdDev", "int32"],
        # ["fns_median", "uint8"],
        # ["fns_median_dry", "uint8"],
        # ["fns_stdDev", "int32"],
        ["slope", "int16"]
    ],

    "agriculture": [
        ['green_p75_saf', 'int16'],
        ['green_max_saf', 'int16'],
        ['green_stdDev_saf', 'int16'],
        ['green_median_saf', 'int16'],
        ['green_qmo_saf', 'int16'],
        ['red_p75_saf', 'int16'],
        ['red_max_saf', 'int16'],
        ['red_stdDev_saf', 'int16'],
        ['red_median_saf', 'int16'],
        ['red_qmo_saf', 'int16'],
        ['nir_p75_saf', 'int16'],
        ['nir_max_saf', 'int16'],
        ['nir_stdDev_saf', 'int16'],
        ['nir_median_saf', 'int16'],
        ['nir_qmo_saf', 'int16'],
        ['swir1_p75_saf', 'int16'],
        ['swir1_max_saf', 'int16'],
        ['swir1_stdDev_saf', 'int16'],
        ['swir1_median_saf', 'int16'],
        ['swir1_qmo_saf', 'int16'],
        ['swir2_p75_saf', 'int16'],
        ['swir2_max_saf', 'int16'],
        ['swir2_stdDev_saf', 'int16'],
        ['swir2_median_saf', 'int16'],
        ['swir2_qmo_saf', 'int16'],
        ['evi2_p20_ent', 'int16'],
        ['evi2_p20_saf', 'int16'],
        ['evi2_p75_saf', 'int16'],
        ['evi2_max_saf', 'int16'],
        ['evi2_min_ent', 'int16'],
        ['evi2_stdDev_saf', 'int16'],
        ['evi2_median_saf', 'int16'],
        ['evi2_cei_annual', 'int16'],
        ['ndwi_p20_ent', 'int16'],
        ['ndwi_p20_saf', 'int16'],
        ['ndwi_p75_saf', 'int16'],
        ['ndwi_max_saf', 'int16'],
        ['ndwi_stdDev_saf', 'int16'],
        ['ndwi_median_saf', 'int16'],
        ['ndwi_qmo_saf', 'int16'],
    ],
    
    "urban": [
        ["blue_median", "uint16"],
        ["green_median", "uint16"],
        ["red_median", "uint16"],
        ["nir_median", "uint16"],
        ["swir1_median", "uint16"],
        ["swir2_median", "uint16"],
        ["tir_median", "uint16"],
        ["tir_min", "uint16"],
        ["tir_max", "uint16"],
        ["ndvi_median", "uint16"],
        ["ndvi_median_p25", "uint16"],
        ["ndvi_median_p75", "uint16"],
        ["ndvi_min", "uint16"],
        ["ndvi_max", "uint16"],
        ["evi_median", "uint16"],
        ["ndwi_median", "uint16"],
        ["mndwi_median", "uint16"],
        ["ndbi_median", "uint16"],
        ["ui_median", "uint16"],   #
        ["bu_median", "uint16"],    #
        ["ebbi_median", "float"],  #
        ["ebbi_min", "float"],  #
        ["ebbi_max", "float"],  #
        ["gv_median", "uint8"],
        ["gvs_median", "uint8"],
        ["npv_median", "uint8"],
        ["soil_median", "uint8"],
        ["cloud_median", "uint8"],
        ["shade_median", "uint8"],
        ["ndfi_median", "uint8"],
        ["veg_small_median", "uint8"],
        ["subs_small_median", "uint8"],
        ["dark_small_median", "uint8"],

    ],
    "indonesia": [
        ["blue_median", "uint16"],
        ["green_median", "uint16"],
        ["green_median_texture", "int16"],
        ["red_median", "uint16"],
        ["nir_median", "uint16"],
        ["swir1_median", "uint16"],
        ["swir2_median", "uint16"],
        ["ndvi_median", "uint16"],
        ["ndwi_median", "uint16"],
        ["evi2_median", "uint16"],
        ["savi_median", "uint16"],
        ["pri_median", "uint16"],
        ["gcvi_median", "int32"],
        ["cai_median", "uint16"],
        ["gv_median", "uint8"],
        ["gvs_median", "uint8"],
        ["npv_median", "uint8"],
        ["npv_stdDev", "int32"],
        ["soil_median", "uint8"],
        ["soil_stdDev", "int32"],
        ["cloud_median", "uint8"],
        ["shade_median", "uint8"],
        ["ndfi_median", "uint8"],
        ["ndfi_median_dry", "uint8"],
        ["ndfi_median_wet", "uint8"],
        ["ndfi_stdDev", "int32"],
        ["sefi_median", "uint8"],
        ["sefi_stdDev", "int32"],
        ["wefi_median", "uint8"],
        ["wefi_median_dry", "uint8"],
        ["wefi_median_wet", "uint8"],
        ["ndvi_median_dry", "uint8"],
        ["ndvi_median_wet", "uint8"],
        ["ndwi_median_dry", "uint8"],
        ["ndwi_median_wet", "uint8"],
        ["slope", "int16"]
    ],
}


def setBandTypes(image, mtype="biomes"):

    def convertDataType(bandSpecification):

        fun = {

            "uint8": lambda image: image.toUint8(),

            "int16": lambda image: image.toInt16(),

            "uint16": lambda image: image.toUint16(),

            "int32": lambda image: image.toInt32(),

            "uint32": lambda image: image.toUint32(),
            
            "float": lambda image: image.toFloat(),


        }

        return fun[bandSpecification[1]](image.select([bandSpecification[0]]))

    bandList = map(convertDataType, BANDS_SPECIFICATIONS[mtype])
    bandList = ee.List(list(bandList))

    image = bandList.iterate(
        lambda band, image: ee.Image(image).addBands(band),
        ee.Image().select()
    )

    return ee.Image(image)
